title:              Ariesan 
email:              lovely.ariesan@gmail.com
description:        Blog Tentang Belajar Coding | Tips & Motivasi Belajar Online
author:             Ariesan
baseurl:            
url:                https://ariesan.github.io/

# Social Profiles
twitter_username:   ElisabethAnggia
github_username:    ariesan
facebook_username:  Anggia.iok23
instagram_username: elisabeth_anggia
linkedin_username:  Elisabeth Anggia Ariestyarini

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-7Q2VEED9RB # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      /posts/page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap #Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag

permalink: none

# default_lang: id-ID
locale: id
timezone: Asia/Jakarta

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: "https-ariesan-github-io"


